FROM node:20-alpine AS base
WORKDIR /app
COPY app/frontend/package*.json ./
RUN npm ci || npm install
COPY app/frontend ./
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=base /app/.next ./.next
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]